import string

#
# Operators
#

SYMBOL_PLUS = '+'
SYMBOL_MINUS = '-'
SYMBOL_MULTIPLY = '*'
SYMBOL_DIVIDE = '/'
SYMBOL_DEGREE = '^'

SYMBOL_BRACKET_OPEN = '('
SYMBOL_BRACKET_CLOSE = ')'

#
# etc.
#

SYMBOL_COMMA1 = '.'
SYMBOL_COMMA2 = ','

SYMBOL_VARIABLE = 'x'

#
# Combinations
#

OPERATORS = [SYMBOL_PLUS, SYMBOL_MINUS, SYMBOL_MULTIPLY, SYMBOL_DIVIDE, SYMBOL_DEGREE]
BRACKETS = [SYMBOL_BRACKET_OPEN, SYMBOL_BRACKET_CLOSE]
COMMAS = [SYMBOL_COMMA1, SYMBOL_COMMA2]
ALPHABET = string.ascii_letters
